-- Initial schema baseline imported from the existing production project.
-- Project ref: oaxhexkpnzcrzssdrbeh
-- Generated in-repo so future changes can flow via migrations (dev -> prod).

create schema if not exists "extensions";
create schema if not exists "graphql";
create schema if not exists "vault";

create extension if not exists "pgcrypto" with schema "extensions";
create extension if not exists "postgis" with schema "extensions";
create extension if not exists "uuid-ossp" with schema "extensions";
create extension if not exists "pg_graphql" with schema "graphql";
create extension if not exists "supabase_vault" with schema "vault";
create extension if not exists "pg_stat_statements" with schema "extensions";

create table if not exists public.organizations (
  organization_id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  name character varying not null
);

create table if not exists public.customers (
  customer_id bigint generated by default as identity primary key,
  organization_id uuid not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  phone text,
  email text,
  notes text,
  created_by uuid not null default auth.uid(),
  constraint customers_organization_id_fkey
    foreign key (organization_id)
    references public.organizations (organization_id)
    on delete cascade
);

create table if not exists public.customer_locations (
  customer_location_id bigint generated by default as identity primary key,
  customer_id bigint,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid(),
  name text not null,
  address text,
  location extensions.geometry not null,
  constraint customer_locations_customer_id_fkey
    foreign key (customer_id)
    references public.customers (customer_id)
    on delete cascade
);

create table if not exists public.profiles (
  user_id uuid primary key,
  system_role text,
  constraint profiles_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete cascade
);

create table if not exists public.organization_members (
  organization_id uuid not null,
  user_id uuid not null,
  role character varying not null default 'member'::character varying,
  created_at timestamp with time zone not null default now(),
  display_name text not null,
  hourly_rate double precision,
  constraint organization_members_pkey primary key (organization_id, user_id),
  constraint organization_members_organization_id_fkey
    foreign key (organization_id)
    references public.organizations (organization_id)
    on delete cascade,
  constraint organization_members_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete cascade
);

create table if not exists public.organization_invitations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  organization_id uuid not null,
  invitee_email text not null,
  invited_by uuid default auth.uid(),
  accepted_at timestamp with time zone,
  token uuid not null default gen_random_uuid(),
  expires_at timestamp with time zone,
  constraint organization_invitations_token_key unique (token),
  constraint organization_invitations_organization_id_fkey
    foreign key (organization_id)
    references public.organizations (organization_id)
    on delete cascade
);

create table if not exists public.projects (
  project_id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null default auth.uid(),
  start_time timestamp with time zone,
  project_status bigint not null default '0'::bigint,
  title text,
  description text,
  updated_at timestamp with time zone default now(),
  customer_id bigint not null,
  customer_location_id bigint not null,
  constraint projects_organization_id_fkey
    foreign key (organization_id)
    references public.organizations (organization_id)
    on delete cascade,
  constraint projects_created_by_fkey
    foreign key (created_by)
    references auth.users (id),
  constraint projects_customer_id_fkey
    foreign key (customer_id)
    references public.customers (customer_id)
    on delete cascade,
  constraint projects_customer_location_id_fkey
    foreign key (customer_location_id)
    references public.customer_locations (customer_location_id)
    on delete cascade
);

create table if not exists public.project_assignees (
  project_id uuid not null default gen_random_uuid(),
  user_id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  organization_id uuid not null,
  constraint project_assignees_pkey primary key (project_id, user_id),
  constraint project_assignees_project_id_fkey
    foreign key (project_id)
    references public.projects (project_id)
    on delete cascade,
  constraint project_assignees_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete cascade,
  constraint project_assignees_organization_id_fkey
    foreign key (organization_id)
    references public.organizations (organization_id)
    on delete cascade
);

create table if not exists public.project_status_history (
  project_status_history_id uuid primary key default gen_random_uuid(),
  project_id uuid not null,
  old_status bigint not null,
  new_status bigint not null,
  changed_at timestamp with time zone not null default now(),
  changed_by uuid not null default auth.uid(),
  constraint project_status_history_project_id_fkey
    foreign key (project_id)
    references public.projects (project_id)
    on delete cascade
);

create table if not exists public.project_time_log_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  project_id uuid not null,
  date date not null,
  hours smallint,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default (now() at time zone 'utc'::text),
  constraint project_time_log_entries_project_id_fkey
    foreign key (project_id)
    references public.projects (project_id)
    on delete cascade,
  constraint project_time_log_entries_project_user_date_key
    unique (project_id, user_id, date)
);

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.accept_invitation_by_token(p_token uuid, p_display_name text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_inv record;
BEGIN
  -- Fetch the pending invitation, locking the row
  SELECT id, organization_id
  INTO v_inv
  FROM organization_invitations
  WHERE token = p_token
    AND accepted_at IS NULL
    AND (expires_at IS NULL OR expires_at > now())
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invitation not found or already used';
  END IF;

  -- Verify the invitation belongs to the calling user's email
  IF NOT EXISTS (
    SELECT 1 FROM organization_invitations
    WHERE id = v_inv.id
      AND invitee_email = auth.email()
  ) THEN
    RAISE EXCEPTION 'Invitation does not match your account';
  END IF;

  -- Add to org (ignore if already a member)
  INSERT INTO organization_members (organization_id, user_id, role, display_name)
  VALUES (v_inv.organization_id, auth.uid(), 'member', p_display_name)
  ON CONFLICT (organization_id, user_id) DO NOTHING;

  -- Delete the invitation
  DELETE FROM organization_invitations WHERE id = v_inv.id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_invitation_by_token(p_token uuid)
 RETURNS TABLE(id bigint, organization_id uuid, organization_name text, invitee_email text, expires_at timestamp with time zone, accepted_at timestamp with time zone)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    i.id,
    i.organization_id,
    o.name AS organization_name,
    i.invitee_email,
    i.expires_at,
    i.accepted_at
  FROM organization_invitations i
  JOIN organizations o USING (organization_id)
  WHERE i.token = p_token
    AND i.accepted_at IS NULL
  LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_org_ids()
 RETURNS SETOF uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT organization_id FROM organization_members WHERE user_id = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.is_assigned_to_project(p_project_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM project_assignees
    WHERE project_id = p_project_id
      AND user_id = auth.uid()
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_org_admin_for_project(p_project_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM projects p
    JOIN organization_members om
      ON om.organization_id = p.organization_id
     AND om.user_id = auth.uid()
     AND om.role = 'admin'
    WHERE p.project_id = p_project_id
  );
$function$
;

CREATE OR REPLACE FUNCTION public.log_project_status_change()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  -- Only log when status actually changes
  if new.project_status is distinct from old.project_status then
    insert into project_status_history (
      project_status_history_id,
      project_id,
      old_status,
      new_status,
      changed_at,
      changed_by
    )
    values (
      gen_random_uuid(),
      old.project_id,
      old.project_status,
      new.project_status,
      now(),
      auth.uid()
    );
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.user_is_admin_in_organization(given_user_id uuid, given_organization_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE
AS $function$BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM organization_members om
    WHERE om.organization_id = given_organization_id
      AND om.user_id = given_user_id
      AND om.role = 'admin'
  )
  OR EXISTS (
    SELECT 1
    FROM profiles p
    WHERE p.user_id = given_user_id
      AND p.system_role = 'dev'
  );
END;$function$
;

CREATE OR REPLACE FUNCTION public.user_is_part_of_organization(given_user_id uuid, given_organization_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE
AS $function$BEGIN
  RETURN EXISTS ( 
    SELECT 1
    FROM organization_members om
    WHERE om.organization_id = given_organization_id
      AND om.user_id = given_user_id
  );
END;$function$
;

-- Idempotent: prod may already have this trigger from pre-migration setup.
drop trigger if exists project_status_history_trigger on public.projects;
create trigger project_status_history_trigger after update on public.projects for each row execute function public.log_project_status_change();

alter table public.customer_locations enable row level security;
alter table public.customers enable row level security;
alter table public.organization_invitations enable row level security;
alter table public.organization_members enable row level security;
alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.project_assignees enable row level security;
alter table public.project_status_history enable row level security;
alter table public.project_time_log_entries enable row level security;
alter table public.projects enable row level security;

-- Idempotent: baseline may run against a DB that already had these policies (pre-migration prod).
drop policy if exists "org admins can delete customer_locations" on public.customer_locations;
drop policy if exists "org admins can insert customer_locations" on public.customer_locations;
drop policy if exists "org admins can update customer_locations" on public.customer_locations;
drop policy if exists "org members can view customer_locations" on public.customer_locations;

drop policy if exists "org admins can delete customers" on public.customers;
drop policy if exists "org admins can insert customers" on public.customers;
drop policy if exists "org admins can update customers" on public.customers;
drop policy if exists "org members can view customers" on public.customers;

drop policy if exists "Admins can create invitations" on public.organization_invitations;
drop policy if exists "Invitee can accept their own invitation" on public.organization_invitations;
drop policy if exists "Invitees can delete their own invitations" on public.organization_invitations;
drop policy if exists "Invitees can view their own invitations" on public.organization_invitations;
drop policy if exists "Public can read pending invitations by token" on public.organization_invitations;
drop policy if exists only_admins_can_invite_to_their_org on public.organization_invitations;

drop policy if exists "Admins can handle members" on public.organization_members;
drop policy if exists "Enable users to view their own data only" on public.organization_members;
drop policy if exists "Org members can view their org members" on public.organization_members;
drop policy if exists "Users can join via invitation" on public.organization_members;
drop policy if exists "users can insert themselves as member" on public.organization_members;

drop policy if exists "Authenticated users can view organizations" on public.organizations;
drop policy if exists "dev users can insert organizations" on public.organizations;
drop policy if exists "only handle my organizations" on public.organizations;

drop policy if exists "Everyone can read" on public.profiles;

drop policy if exists "Org members can view project assignees" on public.project_assignees;
drop policy if exists only_assign_in_my_organization_if_admin on public.project_assignees;

drop policy if exists "Users can insert history in their org" on public.project_status_history;
drop policy if exists "Users can view project history in their organization" on public.project_status_history;

drop policy if exists time_log_delete on public.project_time_log_entries;
drop policy if exists time_log_insert on public.project_time_log_entries;
drop policy if exists time_log_select on public.project_time_log_entries;
drop policy if exists time_log_update on public.project_time_log_entries;

drop policy if exists only_create_in_my_orgainzation on public.projects;
drop policy if exists select_my_projects on public.projects;
drop policy if exists update_my_projects on public.projects;

create policy "org admins can delete customer_locations"
on public.customer_locations
as permissive
for delete
to public
using (
  customer_id in (
    select customers.customer_id
    from customers
    where customers.organization_id in (
      select organization_members.organization_id
      from organization_members
      where organization_members.user_id = auth.uid()
        and organization_members.role::text = 'admin'::text
    )
  )
);

create policy "org admins can insert customer_locations"
on public.customer_locations
as permissive
for insert
to public
with check (
  customer_id in (
    select customers.customer_id
    from customers
    where customers.organization_id in (
      select organization_members.organization_id
      from organization_members
      where organization_members.user_id = auth.uid()
        and organization_members.role::text = 'admin'::text
    )
  )
);

create policy "org admins can update customer_locations"
on public.customer_locations
as permissive
for update
to public
using (
  customer_id in (
    select customers.customer_id
    from customers
    where customers.organization_id in (
      select organization_members.organization_id
      from organization_members
      where organization_members.user_id = auth.uid()
        and organization_members.role::text = 'admin'::text
    )
  )
);

create policy "org members can view customer_locations"
on public.customer_locations
as permissive
for select
to public
using (
  customer_id in (
    select customers.customer_id
    from customers
    where customers.organization_id in (
      select organization_members.organization_id
      from organization_members
      where organization_members.user_id = auth.uid()
    )
  )
);

create policy "org admins can delete customers"
on public.customers
as permissive
for delete
to public
using (
  organization_id in (
    select organization_members.organization_id
    from organization_members
    where organization_members.user_id = auth.uid()
      and organization_members.role::text = 'admin'::text
  )
);

create policy "org admins can insert customers"
on public.customers
as permissive
for insert
to public
with check (
  organization_id in (
    select organization_members.organization_id
    from organization_members
    where organization_members.user_id = auth.uid()
      and organization_members.role::text = 'admin'::text
  )
);

create policy "org admins can update customers"
on public.customers
as permissive
for update
to public
using (
  organization_id in (
    select organization_members.organization_id
    from organization_members
    where organization_members.user_id = auth.uid()
      and organization_members.role::text = 'admin'::text
  )
);

create policy "org members can view customers"
on public.customers
as permissive
for select
to public
using (
  organization_id in (
    select organization_members.organization_id
    from organization_members
    where organization_members.user_id = auth.uid()
  )
);

create policy "Admins can create invitations"
on public.organization_invitations
as permissive
for insert
to public
with check (
  exists (
    select 1
    from organization_members
    where organization_members.organization_id = organization_invitations.organization_id
      and organization_members.user_id = auth.uid()
      and organization_members.role::text = 'admin'::text
  )
);

create policy "Invitee can accept their own invitation"
on public.organization_invitations
as permissive
for update
to public
using (invitee_email = auth.jwt() ->> 'email'::text);

create policy "Invitees can delete their own invitations"
on public.organization_invitations
as permissive
for delete
to public
using (invitee_email = auth.jwt() ->> 'email'::text);

create policy "Invitees can view their own invitations"
on public.organization_invitations
as permissive
for select
to public
using (invitee_email = auth.jwt() ->> 'email'::text);

create policy "Public can read pending invitations by token"
on public.organization_invitations
as permissive
for select
to public
using (accepted_at is null);

create policy only_admins_can_invite_to_their_org
on public.organization_invitations
as permissive
for all
to authenticated
using (
  user_is_admin_in_organization(
    (select auth.uid() as uid),
    organization_id
  )
)
with check (
  user_is_admin_in_organization(
    (select auth.uid() as uid),
    organization_id
  )
);

create policy "Admins can handle members"
on public.organization_members
as permissive
for all
to authenticated
using (
  user_is_admin_in_organization(
    (select auth.uid() as uid),
    organization_id
  )
)
with check (
  user_is_admin_in_organization(
    (select auth.uid() as uid),
    organization_id
  )
);

create policy "Enable users to view their own data only"
on public.organization_members
as permissive
for select
to authenticated
using ((select auth.uid() as uid) = user_id);

create policy "Org members can view their org members"
on public.organization_members
as permissive
for select
to public
using (
  organization_id in (select get_my_org_ids() as get_my_org_ids)
  or user_is_admin_in_organization((select auth.uid() as uid), organization_id)
);

create policy "Users can join via invitation"
on public.organization_members
as permissive
for insert
to public
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from organization_invitations
    where organization_invitations.organization_id = organization_members.organization_id
      and organization_invitations.invitee_email = auth.jwt() ->> 'email'::text
      and organization_invitations.accepted_at is null
  )
);

create policy "users can insert themselves as member"
on public.organization_members
as permissive
for insert
to authenticated
with check (user_id = auth.uid());

create policy "Authenticated users can view organizations"
on public.organizations
as permissive
for select
to public
using (auth.role() = 'authenticated'::text);

create policy "dev users can insert organizations"
on public.organizations
as permissive
for insert
to authenticated
with check (
  exists (
    select 1
    from profiles
    where profiles.user_id = auth.uid()
      and profiles.system_role = 'dev'::text
  )
);

create policy "only handle my organizations"
on public.organizations
as permissive
for all
to authenticated
using (
  user_is_part_of_organization(
    (select auth.uid() as uid),
    organization_id
  )
)
with check (
  user_is_part_of_organization(
    (select auth.uid() as uid),
    organization_id
  )
);

create policy "Everyone can read"
on public.profiles
as permissive
for select
to authenticated
using (true);

create policy "Org members can view project assignees"
on public.project_assignees
as permissive
for select
to public
using (
  exists (
    select 1
    from projects p
    join organization_members om on om.organization_id = p.organization_id
    where p.project_id = project_assignees.project_id
      and om.user_id = auth.uid()
  )
);

create policy only_assign_in_my_organization_if_admin
on public.project_assignees
as permissive
for all
to authenticated
using (
  user_is_admin_in_organization(
    (select auth.uid() as uid),
    organization_id
  )
)
with check (
  user_is_admin_in_organization(
    (select auth.uid() as uid),
    organization_id
  )
);

create policy "Users can insert history in their org"
on public.project_status_history
as permissive
for insert
to authenticated
with check (
  project_id in (
    select p.project_id
    from projects p
    join organization_members om on om.organization_id = p.organization_id
    where om.user_id = auth.uid()
  )
);

create policy "Users can view project history in their organization"
on public.project_status_history
as permissive
for select
to public
using (
  project_id in (
    select p.project_id
    from projects p
    join organization_members om on om.organization_id = p.organization_id
    where om.user_id = auth.uid()
  )
);

create policy time_log_delete
on public.project_time_log_entries
as permissive
for delete
to authenticated
using (
  user_id = auth.uid()
  and (is_assigned_to_project(project_id) or is_org_admin_for_project(project_id))
);

create policy time_log_insert
on public.project_time_log_entries
as permissive
for insert
to authenticated
with check (
  user_id = auth.uid()
  and (is_assigned_to_project(project_id) or is_org_admin_for_project(project_id))
);

create policy time_log_select
on public.project_time_log_entries
as permissive
for select
to authenticated
using (is_assigned_to_project(project_id) or is_org_admin_for_project(project_id));

create policy time_log_update
on public.project_time_log_entries
as permissive
for update
to authenticated
using (
  user_id = auth.uid()
  and (is_assigned_to_project(project_id) or is_org_admin_for_project(project_id))
)
with check (
  user_id = auth.uid()
  and (is_assigned_to_project(project_id) or is_org_admin_for_project(project_id))
);

create policy only_create_in_my_orgainzation
on public.projects
as permissive
for all
to authenticated
using (
  user_is_admin_in_organization(
    (select auth.uid() as uid),
    organization_id
  )
)
with check (
  user_is_admin_in_organization(
    (select auth.uid() as uid),
    organization_id
  )
);

create policy select_my_projects
on public.projects
as permissive
for select
to authenticated
using (is_assigned_to_project(project_id));

create policy update_my_projects
on public.projects
as permissive
for update
to authenticated
using (is_assigned_to_project(project_id))
with check (is_assigned_to_project(project_id));

grant usage on schema public to anon, authenticated, service_role;
grant all privileges on all tables in schema public to anon, authenticated, service_role;
grant usage, select, update on all sequences in schema public to anon, authenticated, service_role;
grant execute on all functions in schema public to anon, authenticated, service_role;
